#!/usr/bin/php
<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . "AutoLoader.php";

$server = \Lay\core\LayConfig::res_server();
$root = $server->root;
$temp = $server->temp;
$command = file_exists($root . "composer.lock") ? "update" : "install";

exec("export HOME=$root && cd $root && composer $command 2>&1", $out);

file_put_contents($temp . "deploy_composer_output.txt", implode("\n", $out));

// unset cron job after updating composer packages
\Lay\libs\LayCron::new()->unset("update-composer-pkgs");
